### ISSUE TITLE
[Feature Request] Include bypass for Enforced Config

### ISSUE THREAD

**Issue by Graphite23** [Orange-Cyberdefense/KeePwn#2]
As described [here ](https://sourceforge.net/p/keepass/discussion/329220/thread/a146e5cf6b/?page=3#fd7f),
Please add the ability to detect the presence of an enforced config file in an unwritable protected keepass directory (e.g. Program Files).
If detected, copy the keepass application directory to the writeable user profile directory and alter the config with the export trigger.  Then search for, and modify, any .lnk keepass shortcuts located in the user's profile (Desktop, Start Menu Programs, Taskbar).

**Comment by d3lb3** [comment]
KeePwn requires administrator access to extract entries from a target machine, so I don't really see the point of looking for "unwritable protected keepass directory" (which would not be from KeePwn's perspective).

In addition, as stated on the SourceForge thread you linked to the feature request, once you are administrator of the machine there are basically no limit regarding how you can extract passwords: replacing one of KeePass' DLL by a malicious one, editing the enforced configuration file, replacing KeePass itself by an older vulnerable version..

Instead of implementing every single technique I could think of, I decided to stay focused on the plugin extraction one, which is efficient and well-tested (see: https://github.com/d3lb3/KeeFarceReborn) .

While other techniques may be interesting, I consider them more of edge-cases for specific situations where plugin extraction is blocked, which in my experience is very rare.
